name: hashchat_client
description: A Burner Chat Client with Liquid Glass Design.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # UI
  glassmorphism: ^3.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  intl: ^0.19.0
  # Crypto
  web3dart: ^2.7.0
  encrypt: ^5.0.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  pointycastle: ^3.7.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
